### ISSUE TITLE
[bug]不能导入文件

### ISSUE THREAD

**Issue by 775146061** [crustio/crust-apps#194]
点击导入随便上传一个文件就报下面的错误，麻烦看一下
![image](https://user-images.githubusercontent.com/22257014/123435195-e2009d80-d5ff-11eb-9817-7f69a2e106a7.png)

**Comment by zhangchenxu** [comment]
![image](https://user-images.githubusercontent.com/16740033/123437165-f6de3080-d601-11eb-9f79-016fa4a8e9f9.png)
